[package]
name = "capital_gain_tax_ireland"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
calamine = "0.26.1"
csv = "1.3.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
time = {version = "0.3.36", features = ["parsing", "formatting", "macros"]}
